name: MI-PBR
input:
  format: raw
profiles:
- edition: Java
  format: 9
  name: MI-LabPbr
  description: A short description of the RP content.
  encoding:
    format: lab-1.3
  block-texture-size: 16
