name: MI-PBR
input:
  format: raw
profiles:
- edition: Java
  format: 15
  name: MI-LabPbr
  description: ''
  encoding:
    format: lab-1.3
    enable-palette: false
  block-texture-size: 16
- edition: Java
  format: 15
  name: MI-OldPbr
  description: ''
  encoding:
    format: old-pbr
  block-texture-size: 16
