name: Release
on: workflow_dispatch

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: true

  publish_labPbr:
    name: Publish LabPbr
    runs-on: ubuntu-latest
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPBR
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: MI-LabPBR
          zip: MI-LabPBR-v${{ github.run_number }}.zip
      - name: Compile OldPBR
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: MI-OldPBR
          zip: MI-OldPBR-v${{ github.run_number }}.zip
      - name: Release OldPBR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./MI-OldPBR-v${{ github.run_number }}.zip
          asset_name: MI-OldPBR-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Publish to CurseForge, Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: MI-PBR v${{ github.run_number }}
          version: v${{ github.run_number }}
          version-type: beta
          changelog: "###Release v${{ github.run_number }}"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: <TODO>
          modrinth-featured: true
          modrinth-loaders: minecraft
          curseforge-token: ${{ secrets.CF_API_TOKEN }}
          curseforge-id: <TODO>
          loaders: |
            fabric
            forge
            quilt
          files: |
            MI-LabPBR-v${{ github.run_number }}.zip
            MI-OldPBR-v${{ github.run_number }}.zip
